### ISSUE TITLE
[pdm/meta] The output refs seem to be wrong

### ISSUE THREAD

**Issue by niooss-ledger** [LedgerHQ/actions#144]
Hello,
While trying to understand what `pdm/meta` is doing, I am struggling with something that I fail to understand. Here are three questions I have, which would help me better understand what is going on.

At the beginning of the action file, some outputs are defined: https://github.com/LedgerHQ/actions/blob/754e561740cf754c58a9040d8a0ea2a23249f224/pdm/meta/action.yml#L12-L24

=> Question 1. Why is the output `has_coverage` using `outputs.tests` instead of  `output.coverage`?

Then, the action actually computes the outputs: https://github.com/LedgerHQ/actions/blob/754e561740cf754c58a9040d8a0ea2a23249f224/pdm/meta/action.yml#L41-L51

=> Question 2. These outputs are names `has_...`. Do the variables defined in `output` *auto-magically* add a `has_` prefix?

Finally, the action computes some outputs in a step named `refs`, which are not referenced in the beginning.

=> Question 3. Should the beginning of the action also document `target`, `branch`, `version` and `sha`?

Could you please take a look?

**Comment by noirbizarre** [comment]
Hello 👋🏼 

> Question 1. Why is the output has_coverage using outputs.tests instead of output.coverage

This is obviously an error

> Question 2. These outputs are names has_.... Do the variables defined in output auto-magically add a `has_` prefix?

Yes, this is how are defined outputs in Github Actions. A bit weird (you write to the `$GITHUT_OUTPUT` file and each affectation become an output) but working.

> Question 3. Should the beginning of the action also document `target`, `branch`, `version` and `sha`?

This part was a legacy step from the `Pipenv` based action. They are not referenced because the resulting pdm actions were not using it.

TBH, `pdm/meta` was crafted at start then not touched anymore. I also encountered some issues where I need some of those data and the current approach is broken.

I plan to submit a PR integrating `pdm/meta` to `pdm/init` so outputs are on the init step and available to every step after. This should reduce the amount of used workers for a single workflow as well as allowing to skip some useless steps without having a lot of variables to pass to each action (my case: I have a non-library project which I can't release because release is expected openapi which is not present for this one).
I can reexpose the `refs` if you need it.

Would this be OK for you ?

**Comment by niooss-ledger** [comment]
I confirm PR #145 works fine (tested in https://github.com/LedgerHQ/dnswatcher/pull/141). Thanks!
